[package]
name = "arrow-udf-python"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/risingwavelabs/arrow-udf"
keywords = ["arrow", "udf", "python"]
license = "Apache-2.0"

[dependencies]
anyhow = "1"
arrow-array = ">=50"
arrow-buffer = ">=50"
arrow-ipc = ">=50"
arrow-schema = ">=50"
lazy_static = "1"
pyo3 = "0.20"

[build-dependencies]
pyo3-build-config = "0.20"

[dev-dependencies]
arrow-cast = { version = ">=50", features = ["prettyprint"] }
expect-test = "1"
